### ISSUE TITLE
accession number not matching with taxa ID

### ISSUE THREAD

**Issue by ngeraldi** [sherrillmix/taxonomizr#10]
Hello, I just updated to the newest version of taxonomizr and ran the new code to create the sql. I have about 200,000 accession number from searching ncbi for rbcl genes.  I have tried both the base and version of accession numbers and they do not seem to be matching up correctly, they get some but not all the taxa Ids (the accession number has a taxa id if I search them directly in ncbi).  Could you check to see if you are having the same problem? Attached is a link to the dataframe of accession numbers (taxa id are from entrez code, but would like to use your much faster functions) and example code is below.  
It is worth mentioning that getTaxonomy() works once I get the taxa ID from entrez code.

I have gotten around the issue, so no hurry, but it would be nice to figure out the problem so I don't need to wait hours on entrez functions.
thank you
Nathan

https://www.dropbox.com/s/ivygvjqb0zfa6rl/ncbi_rbcl_lineage.csv?dl=0
x<-data.table::fread(file="ncbi_rbcl_lineage.csv",header = T,sep=",")
accessionToTaxa(x$accession[1:100],"accessionTaxa.sql",version='base')

output

  [1] 2478980 2478980 2478980   88415   88415   88415   88415 1191690 1191690 1191690 1077399 1077399 1077399
 [14] 1077399 1077399 1077399      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
 [27]      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
 [40]      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA
 [53]      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      NA 1486651
 [66] 1486654 1486646 1486646 1486646 1486654 1486646  373125 1486654 1486654 1486654 1486654 1486646  373125
 [79]  373125  373125 1486646 1486646 1486646 1486646 1486646 1486646  373124  373124  340433 1486647 1486650
 [92] 1486650  373124  373124 1486647 1486647 1486646 1486647 1486650 1486646
Warning messages:
1: In file.remove(tmp) :
  cannot remove file 'C:\Users\geraldn\AppData\Local\Temp\RtmpM31OhV\file219c75ba49a3', reason 'Permission denied'
2: In file.remove(tmp) :
  cannot remove file 'C:\Users\geraldn\AppData\Local\Temp\RtmpM31OhV\file219c75ba49a3', reason 'Permission denied'

**Comment by sherrillmix** [comment]
My first guess would be that those NAs are from recently uploaded sequences and that a fresh database download from NCBI would catch them but that's just a guess. I'm downloading a fresh database copy and will update once that finishes.

**Comment by sherrillmix** [comment]
So if I do:

```R
library(taxonomizr)
x<-read.csv('ncbi_rbcl_lineage.csv',stringsAsFactors=FALSE)
taxaId<-accessionToTaxa(x$accession,'db/taxo/nameNode.sqlite','base')
summary(is.na(taxaId))
range(which(is.na(taxaId)))
```

I get 602 NAs and 221,618 good taxa IDs and I see that the 602 NAs are all in the first 800 entries of your .csv. Just eyeballing a couple they seem to have a recent [modification date]( https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html#ModificationDateB) e.g.:
[MF070051](https://www.ncbi.nlm.nih.gov/nuccore/MF070051.1)
[MH104899](https://www.ncbi.nlm.nih.gov/nuccore/MH104899)
[MH748856](https://www.ncbi.nlm.nih.gov/nuccore/MH748856)
and do not show up in a zgrep of the raw accession2taxid.gz files. So I'm going to lay the blame on delays in new data percolating through NCBI into the downloadable archives and suggest waiting a few days and redownloading the archives. 

Or are you having a problem different than I'm seeing here?

**Comment by ngeraldi** [comment]
I am getting the exact same results. Guess I just need to be more patient.
Thanks for the quick reply.
Best
Nathan

**Comment by sherrillmix** [comment]
I was curious so I redownloaded the database today (4 days later). Now I'm getting 222,172 good IDs and only 48 NAs. The 48 NAs are all in the first 64 entries of the .csv. That seems to reinforce that we're just seeing delay in data moving through the NCBI pipelines.

Thanks for the report and good luck with your project.

**Comment by sankadinesh** [comment]
Dear All,
can anyone please give me a script for import and export through .csv format. I am creating custom database of 35k sequences. Thanks 
Regards,
Dinesh S L

**Comment by salix-d** [comment]
I know this is an old issue, but I found it the other day because I had similar results but for a different reason.

In my case, I was trying yo update the taxonomy of a local database and the NA that it returned were because the records had been removed from the ncbi database (for example, this one : https://www.ncbi.nlm.nih.gov/nuccore/JF276405.1?report=genbank). So NAs aren't always a bad result.
And it's something other packages connecting to the website didn't catch as they returned me the info for the removed sequences anyway.

**Comment by sherrillmix** [comment]
Thanks for the information. Glad to hear it's working well. Out of curiosity, what other packages are you using?

**Comment by salix-d** [comment]
I was comparing with the packages taxa and taxize.

**Comment by sherrillmix** [comment]
Thanks for the info. I haven't looked around for other tools in a while. It'll be interesting to see how those compare.

**Comment by salix-d** [comment]
They're good if you can't store a database on your PC/server, but they take much longer to return the results. So if you need to do that a lot having the database made once saves you some time imo.

But I realised yesterday, that none of the packages were giving me the 'incertae sedis' taxons because they're always with 'no rank' in the NCBI database.

But since, I'm using this to make a taxonomy file for the assignTaxnomy function in Dada2, I do need them since it would help in the assignment of taxonomy. (giving another rank would help differentiate between the 'uncultured/sp MB12' type  and the actual named species we just don't know where to put yet).

I did find a work around though by adding this to the loop in the getTaxonomy function :
 ```
     is.incertae = grep('incertae sedis', parents$name)
      if(length(is.incertae) > 0){
        for(i in is.incertae){
          rank <- colnames(taxaDf)[which(!is.na(taxaDf[i,]))[1] - 1]
          taxaDf[i, rank] <- parents$name[i] 
        }
```
