### ISSUE TITLE
Error prepareDatabase

### ISSUE THREAD

**Issue by cgandini** [sherrillmix/taxonomizr#11]
Hi, I am getting the following error:

> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
Content type 'unknown' length 46768956 bytes (44.6 MB)
=
downloaded length 1119304 != reported length 46768956URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz': status was 'Transferred a partial file'Error in utils::download.file(url, tarFile, mode = "wb") : 
  cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'

Do you know how to fix it?

Many thanks!

Carolina

**Comment by sherrillmix** [comment]
That sounds like you a downloading problem. You didn't happen to lose internet connection while you were downloading, did you? Otherwise perhaps the NCBI server had a hiccup and disconnected early. 

Would you mind repeating the command one more time to make sure it wasn't just a freak event?

If repeating, doesn't fix it. Could you visit ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz in your browser, download the linked file and see what size the file is reported as (should be about 44Mb)?

**Comment by sherrillmix** [comment]
I'm going to close this one until further feedback. Feel free reopen if you have any further issues.
