### ISSUE TITLE
Database or disk is full error

### ISSUE THREAD

**Issue by ptskidmore** [sherrillmix/taxonomizr#19]
Hi there,

I am trying to build the sql database manually since I need to use the protein accessions and am getting the error:

`Error in result_create(conn@ptr, statement) : database or disk is full`
`Calls: read.accession2taxid ... .local -> new -> initialize -> initialize -> result_create`
`Execution halted`

I have changed the R temp directory to a drive with plenty of storage (~200TB) and am still running into this issue.

This is how I am building the database:

`getNamesAndNodes()`
`getAccession2taxid()`
`getAccession2taxid(types='prot')`
`read.names.sql('names.dmp', 'accessionTaxa.sql')`
`read.nodes.sql('nodes.dmp', 'accessionTaxa.sql')`
`read.accession2taxid(list.files('.','accession2taxid.gz$'), 'accessionTaxa.sql')`

I have tried this on multiple different servers and computers with no luck. Please let me know what you think.

-Peter Skidmore

**Comment by sherrillmix** [comment]
Thanks for the bug report. I just tried your exact commands and it ran to completion on my computer. Could you give me a little more info? Maybe post the return of `sessionInfo()` so we can narrow down OS, R version and package version. And `tempdir()` to see if temp is where it should be?

This sounds similar to Issue #5 and so might be fixed by starting R with `TMPDIR=/path/to/tmp R` then running commands as usual.

**Comment by ptskidmore** [comment]
Thank you for your response.

Changing the temp directory worked.

**Comment by sherrillmix** [comment]
Great. Thanks for letting me know. Good luck with your research.
