### ISSUE TITLE
Error with prepareDatabase: RS_sqlite_import: expected 3 columns but found 4 

### ISSUE THREAD

**Issue by MaikeHu** [sherrillmix/taxonomizr#20]
Dear Sherrillmix,
I am trying to use taxonomize to find the taxonomic information for NCBI accession numbers, but cannot proceed past the prepareDatabase step, which throws an error every time (see below). I am running R 4.0.3 in Rstudio on a Windows 10 computer and have ensured there is enough room on the hardrive and in the temp directory. I can also see the file created by this command in the directory. I have also tried to solve it as stated in other issues, but to no avail. Is there a way to fix this?

> prepareDatabase("accessionTaxa.sql") # prepare the NCBI database - large, put in ext. harddrive!
> Downloading names and nodes with getNamesAndNodes()
> ./names.dmp, ./nodes.dmp already exist. Delete to redownload
> Downloading accession2taxid with getAccession2taxid()
> This can be a big (several gigabytes) download. Please be patient and use a fast connection.
> ./nucl_gb.accession2taxid.gz, ./nucl_wgs.accession2taxid.gz already exist. Delete to redownload
> Preprocessing names with read.names.sql()
> Preprocessing nodes with read.nodes.sql()
> Preprocessing accession2taxid with read.accession2taxid()
> Reading ./nucl_gb.accession2taxid.gz.
> Reading ./nucl_wgs.accession2taxid.gz.
> Reading in values. This may take a while.
> Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
>   RS_sqlite_import: D:/RPC_SpiderGut/rtemp\RtmpmSWBo9\file341c33f67f6 line 122996989 expected 3 columns of data but found 4
> In addition: There were 50 or more warnings (use warnings() to see the first 50)

Thank you in advance for your help!
-Maike

**Comment by sherrillmix** [comment]
When I tried to replicate this, the package was having some difficulty downloading from the NCBI servers. Several downloads failed with errors like `downloaded length 3602997792 != reported length 3635172956` with the exact downloaded length varying. I wonder if NCBI was having some sort of problems. 

It's a pain since it takes so long but could you delete the access2taxid.gz files and repeat to see if it was a corrupted download? Failing that could you post the results of `sessionInfo()` just in case the exact package versions involved provides any information. Also maybe the file sizes of the .accession2taxid.gz files to see if they seem reasonable.
