### ISSUE TITLE
read.accession2taxid failing

### ISSUE THREAD

**Issue by dleopold** [sherrillmix/taxonomizr#26]
I am having trouble getting `read.accession2taxid()` to complete properly on a remote server (it worked fine on my local laptop). When I run the command I get this error:

```
> read.accession2taxid(list.files('.','accession2taxid.gz$'),'NCBI_accessionTaxa_20210211.sql')
Reading nucl_gb.accession2taxid.gz.
Reading nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: /tmp/RtmpuEFbGo/file48e13a73756 line 119051393 expected 3 columns of data but found 1
In addition: There were 50 or more warnings (use warnings() to see the first 50)

> warnings()
Warning messages:
1: In writeBin(bfr, con = out, size = 1L) : problem writing to connection
```

It is not a read/write permissions issue, though maybe it could be an issue with the size of sqlite temp files? I tried to set the sqlite temp directory to a location with more space with:

`> Sys.setenv(SQLITE_TMPDIR = "/mnt/efs/")`

but it still seems to be writing to `/tmp`. In any case, I am not even sure it is a size issue because there are no huge files in `/tmp `when the function fails. Any ideas to solving this issue would be appreciated.

**Comment by sherrillmix** [comment]
That does sound like a out of space issue. It seems writeBin fails without erroring out and then when taxonomizr goes to read in the file, it finds an incorrectly formatted final line (thanks to the truncation). I should check to see if there's a way to make it fail more assertively. 

But for now, getting SQLite to listen to your temp assignments seems surprisingly hard. I always have to play around before I get it right but this sounds similar to Issue #5 and so might be fixed by starting R with `TMPDIR=/path/to/tmp R` (instead of starting R by typing `R <return>`, type all that instead) then running commands as usual.

**Comment by dleopold** [comment]
Thank you for the quick reply. It took a few tries, but I got it to work. In addition to setting the temp path on starting R (setting them with Sys.setev did not work), I also ran into a problem because R was being run as `sudo` due to an alias for the `R` command on the system. Removing the alias so R would run as a regular user and then setting all of the possible temp directory variables at startup (probably not all needed, but I was covering my bases) worked for me:

`> SQLITE_TMPDIR=/mnt/ef/tmp TMPDIR=/mnt/efs/tmp TMP=/mnt/efs/tmp R`

**Comment by sherrillmix** [comment]
Thanks for the update. I'm glad you figured it out because I would not have been guessing `R` aliased to `sudo R` any time soon.  I'll keep that in mind the next time that comes up though. Nice debugging and good luck with your research.
