### ISSUE TITLE
prepareDatabase() and getAccession2taxid()  curl error -  server did not report OK, got 450

### ISSUE THREAD

**Issue by elaine-shen** [sherrillmix/taxonomizr#33]
Hello,

I tried to prepare the SQLite database using both prepareDatabase() and the manual steps, specifically getAccession2taxid(), and get the same error ("Error in curl::curl_download(xx, yy, mode = "wb", quiet = FALSE) : server did not report OK, got 450"). Do you have any solutions for why this is happening? I looked at other questions on the forum, and this error seems unique. 

Thanks for all your help, in advance! 

```
> prepareDatabase('accessionTaxa.sql') 
Downloading names and nodes with getNamesAndNodes()
 [100%] Downloaded 55185775 bytes...
 [100%] Downloaded 49 bytes...
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
 [100%] Downloaded 2053095811 bytes...
Error in curl::curl_download(xx, yy, mode = "wb", quiet = FALSE) : 
  server did not report OK, got 450


> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxonomizr_0.8.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        DBI_1.1.1         RSQLite_2.2.3     rlang_0.4.10      cachem_1.0.4     
 [6] curl_4.3          data.table_1.14.0 blob_1.2.1        vctrs_0.3.6       tools_4.0.3      
[11] bit64_4.0.5       tinytex_0.29      bit_4.0.4         fastmap_1.1.0     xfun_0.21        
[16] parallel_4.0.3    compiler_4.0.3    pkgconfig_2.0.3   memoise_2.0.0 
```

**Comment by sherrillmix** [comment]
I just ran the same command and didn't encounter this error. It looks like 2053095811 bytes is the correct size for the file so perhaps not a problem with the big download. Apparently a 450 FTP error is:

> A 450 response code may be sent in response to any command requiring the server to access a local file. It is a transient negative response as the error is considered a temporary one. It is usually sent when the FTP server is unable to gain access to a required file at the time the command is received. In this case, the client is encouraged to restart the FTP transaction and try again.

I guess my first guess is a hiccup from the NCBI servers (unfortunately not too uncommon). If you clear out the directory and repeat the command a time or two, do you get a different outcome?

**Comment by elaine-shen** [comment]
Thanks for your prompt response! Sadly I've tried a couple of times, and while I do get the `accessionTaxa.sql` file in my directory (though it's only 391.6 mb), taxonomizr is unable to recognize it when I try to use it in the proper directory:

```
> ids = accessionToTaxa(unique_acc, 'accessionTaxa.sql')
Error: no such table: accessionTaxa
```

**Comment by elaine-shen** [comment]
Interestingly, when I tried again on my local connection (not logged onto my university connection which produced the initial error), I get the same result but with a different error this time: 

```
> prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
 [100%] Downloaded 55194898 bytes...
 [100%] Downloaded 49 bytes...
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
 [100%] Downloaded 2053095811 bytes...
Error in curl::curl_download(xx, yy, mode = "wb", quiet = FALSE) : 
  Timeout was reached: [] FTP response timeout
```

**Comment by sherrillmix** [comment]
For "Error: no such table: accessionTaxa", the `prepareDatabase` command successfully processed data from the names/nodes file but terminated early from the download error and so did not process the accession IDs into an accessionTaxa table. So that error is what you would expect given the previous error you reported. For reference, accessionTaxa.sql should be in the 60GB range after processing accession IDs.

For the "FTP response timeout", again it seems like something odd is going on in the connection with NCBI and/or their servers. An "FTP response timeout" means that R asked NCBI to download a file but received no response and gave up vs last time when the server responded but said to try again later. I assume you're working on an internet connection that's stable and decently fast?

So I guess I'd ask to repeat again a couple times. That's annoying I know but it seems something random is going on here with the changing error messages so I need a bit more data to try to debug. The errors from a few attempts might start to narrow things down. Alternatively, you could just download the files manually:
  https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz
  https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz
and put them in whatever directory you're working in and prepareDatabase should use them instead of trying to downlpad.

**Comment by elaine-shen** [comment]
Thank you so much for the help. Yes, I am working on an internet connection that's stable and decently fast. The changing errors was because I switched between my home wifi (yielding the Timeout was reached: [] FTP response timeout error) and my university wifi via VPN (yielding the Error in curl::curl_download(xx, yy, mode = "wb", quiet = FALSE) : 
  server did not report OK, got 450 errror). I've tried both a few times before posting this issue, so it's fairly consistent for me. I will download the files manually, for now.

**Comment by sherrillmix** [comment]
Hmm very strange. I just tried again on a Linux and Mac machine and didn't have any luck replicating the bug but there definitely are previous reports of download troubles. It's been a pretty frustrating issue to get a handle on since it seems to be intermittent and location specific. Sorry for the hassle.

If you're still up for debugging, could you perhaps try:
`getAccession2taxid(baseUrl='https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/')`
to see if this could be specific to ftp and switching to http might fix it. If that happened to run to completion, I guess it'd be a good control to move to a new directory or delete/move the downloaded files and try the default ftp version to make sure it still fails :
`getAccession2taxid()`

**Comment by PKatarina** [comment]
Hello,
I am answering in case you are still trying to debug...  
I have the same 450 error as the author (tried 2 times) and managed the download with your solution:
> getAccession2taxid(baseUrl='https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/')

**Comment by sherrillmix** [comment]
Thanks PKatarina. So the default ftp:// failed twice while https:// worked on the first shot. I've been trying to narrow down which is better so that's pretty interesting data. Thank you reporting.

**Comment by RBuesink** [comment]
> Hello, I am answering in case you are still trying to debug... I have the same 450 error as the author (tried 2 times) and managed the download with your solution:
> 
> > getAccession2taxid(baseUrl='https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/')

I've also managed to download the files, but now I'm not sure how to continue. Running prepareDatabase('accessionTaxa.sql') doesn't work, the files are zipped. How do I run from here?
