### ISSUE TITLE
AccessionToTaxa error in file.remove(tmp)

### ISSUE THREAD

**Issue by pollingmarcel** [sherrillmix/taxonomizr#39]
Ho there!

Thanks for your excellent package :) I had it working nicely before I updated my R version to 4.1.2. Now I keep getting an error when I call the accessionToTaxa function using the accessionTaxa.sql database. It looks like the below:

![image](https://user-images.githubusercontent.com/69917434/157430259-065c326b-3970-49b9-80ca-d13fd7ce9039.png)

I wonder if you have seen this before.. it may be just a local permissions thing but my IT department could not figure it out unfortunately.. Maybe you can :) 

Thanks in advance,

Marcel Polling

**Comment by sherrillmix** [comment]
Hmm the good news is that those are just warnings so assuming that's all that's going on then your actual analysis should not be affected. Or were you getting errors downstream of this?

But for more detail, it seems R is complaining that it can not delete files in your temp directory (the taxonomizr functions use a few temporary files to interact with the SQLite database and try to clean up after themselves when finished). But actually it shouldn't matter if they delete or not since the whole temp directory is cleared when R exits. Of course, it may be a general problem that R can not clean up after itself and you start building up a bunch of temp folders but again not the worst since if things did get large you can just go through and delete manually when you're sure you don't have any R sessions doing anything important. 

To test, in the same session you could do something like:

```
tmp<-tempfile()
print(tmp)
file.create(tmp)
file.exists(tmp)
file.remove(tmp)
file.exists(tmp)
```

which should return something like:

```
> tmp<-tempfile()
> print(tmp)
[1] "/tmp/RtmpvYKDuZ/filebdbb5481d2553"
> file.create(tmp)
[1] TRUE
> file.exists(tmp)
[1] TRUE
> file.remove(tmp)
[1] TRUE
> file.exists(tmp)
[1] FALSE
```

Although for you the path for the tempfile return the same `C:\Users\...` as your picture. And I'm guessing that the file.remove will throw the same warning and the final `file.exists` will return TRUE. If so, perhaps look into permissions in the filepath you mentioned. 

You could also considering changing the [temp dir for your R session](https://stackoverflow.com/questions/17107206/change-temporary-directory) (similar to issue #5 although different problem).

**Comment by sherrillmix** [comment]
I'm going to mark closed but definitely let me know if that didn't resolve the issue or you have any other problems. Thanks for the bug report and good luck with your research.

**Comment by pollingmarcel** [comment]
Thanks so much for your help, indeed it is a warning, but as it throwd it
for every record I get quite a log!

I have changed the location where R stored its temp files and that seems to
work!

Met vriendelijke groet,

Marcel Polling
Correspondent
<https://naturalis-public-media-assets.s3.eu-central-1.amazonaws.com/Naturalis-mail-signature/logo.png>






- -
***@***.*** - www.naturalis.nl
Darwinweg 2, 2333 CR Leiden
Postbus 9517, 2300 RA Leiden
<https://www.naturalis.nl/>

**Comment by sherrillmix** [comment]
Yeah I agree it's definitely good to pay attention to and correct warnings and fixing the temp file directory does seem like the best course. 

Just for completeness, if someone else comes across this warning, the ideal case is to fix the permissions issue. If that's not possible they could think about `suppressWarnings()` but that's not great because it suppresses all warnings and something important could be missed. They could instead suppress just this specific warning with something like:
```
checkWarning<-function(w){if(grepl('cannot remove',w$message))invokeRestart('muffleWarning')}
withCallingHandlers(accessionToTaxa(...),warning=checkWarning)
```

For example:
```
> checkWarning<-function(w){if(grepl('cannot remove',w$message))invokeRestart('muffleWarning')}
> withCallingHandlers(warning('cannot remove file'),warning=checkWarning) #no warning is generated
> withCallingHandlers(warning('some other warning'),warning=checkWarning) #warning is generated
Warning message:
In withCallingHandlers(warning("some other warning"), warning = checkWarning) :
  some other warning
```

Thanks again.
