### ISSUE TITLE
sql 4 protein accession: "Error in connection_import_file"

### ISSUE THREAD

**Issue by ferreirafm** [sherrillmix/taxonomizr#42]
I'm trying unsuccessfully to build the sql database to get taxids and species for protein accession codes. Any clues are appreciated.   
The error message is as follows:
`
R » prepareDatabase(types = c('prot'))
Downloading names and nodes with getNamesAndNodes()
./names.dmp, ./nodes.dmp already exist. Delete to redownload
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
./prot.accession2taxid.gz already exist. Delete to redownload
Preprocessing accession2taxid with read.accession2taxid()
Reading ./prot.accession2taxid.gz.
Reading in values. This may take a while.
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: /tmp/Rtmp5fKpXQ/file137afc38c4385f line 134 expected 3 columns of data but found 1
In addition: There were 50 or more warnings (use warnings() to see the first 50)
`

**Comment by sherrillmix** [comment]
I can duplicate this error. In general, it's probably a better idea to paste error messages than post images (a lot easier for anyone with a similar error to find through google) so it's:

```
> prepareDatabase(types='prot')
...
Reading in values. This may take a while.  
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: /tmp/RtmpO8BWK5/file31111c2097f13 line 134 expected 3 columns of data but found 1
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

and the warnings are a bunch of:

```
In writeBin(bfr, con = out, size = 1L) : problem writing to connection
```

I'll try and figure out what's going on there.

**Comment by sherrillmix** [comment]
Ok this issue was a bit stochastic so lots of fun to debug. But I believe this was due to the temp directory silently running out of space. The package uses a C function to quickly remove some unnecessary columns prior to loading into the sqlite database and that function was using `fputc` and `fputc` will happily write to a full file (especially with buffering). I added checks with `ferror` and `fflush` that should keep an eye on that so I believe it should now be "fixed" in the github version of the package and should fail more vocally. So if you run the new version now (and are still low on space), you should get a slightly more vocal error (and would then need to use a larger temp directory for the initial processing).

**Comment by ferreirafm** [comment]
Thanks for helping. The problem has been solved setting the R tmp directory to another location. It can be done editing your local ~/.Renviron as following:
`> echo "TMP = '/home/$USER/tmp'" >> ~/.Renviron`

**Comment by sherrillmix** [comment]
Oh yeah it would have been helpful for me to mention how to completely fix. Sorry tends to come up a lot so forgot I hadn't included in this thread. You're right you can set in .Renviron or start R with a prepended variable `TMP=/PATH/FOR/DIR R`. 

Glad you got it working. Good luck with your research.
