### ISSUE TITLE
`accessionToTaxa` function not converting accession numbers to taxIDs?

### ISSUE THREAD

**Issue by jiwoonp** [sherrillmix/taxonomizr#45]
Hello,

I am having trouble with the `accessionToTaxa` function and was wondering if you had any ideas why this is happening.

I had set up my database using the commands below:

```
getNamesAndNodes(outDir = "F:/R/db")
getAccession2taxid(outDir = "F:/R/db")
prepareDatabase('accessionTaxa.sql')
```

This created these files in my directory:  `names.dmp` (193.3MB), `nodes.dmp` (199.1MB), and `accessionTaxa.sql` (64GB).

I tried to convert the accession numbers to IDs by running this:  `accessionToTaxa(mydata[,2], "accessionTaxa.sql")`
(`mydata` looks like below:
```
> head(mydata[,2], 10)
 [1] "WP_037213762.1" "WP_058500402.1" "WP_143869084.1" "WP_135060942.1" "MBJ15343.1"     "WP_054976553.1" "WP_163853887.1"
 [8] "WP_010503396.1" "WP_036687788.1" "WP_127490283.1"
```
But this returned a vector only with NAs, and I also got these warning messages:

```
Warning messages:
1: In file.remove(tmp) : cannot remove file 'C:\Users\JP\AppData\Local\Temp\Rtmpuwvsuw\file4dec541a158b', reason 'Permission denied'
2: In file.remove(tmp) : cannot remove file 'C:\Users\JP\AppData\Local\Temp\Rtmpuwvsuw\file4dec541a158b', reason 'Permission denied'
```

I have looked into the archived issues and tried creating and deleting a temporary file (as you suggested in issue #39) but the `file.remove(tmp)` did not throw any errors. The results looked like this:

```
> tmp <- tempfile()
> print(tmp)
[1] "C:\\Users\\JP\\AppData\\Local\\Temp\\Rtmpuwvsuw\\file4dec5085282c"
> file.create(tmp)
[1] TRUE
> file.exists(tmp)
[1] TRUE
> file.remove(tmp)
[1] TRUE
> file.exists(tmp)
[1] FALSE
```

I would really appreciate it if you can think of any suggestions to fix this issue, thank you!

**Comment by sherrillmix** [comment]
Your accession numbers look like protein sequences. NCBI stores those in a separate file so you'll probably want to get that file with something like:
prepareDatabase('accessionTaxa.sql',types='prot')

Not sure what's going on with the file remove warnings other than the standard handwave at Windows permission craziness and pointing to the potential solutions of changing the temp directory or suppressing that particular warning as in #39. But that's unlikely to be the root cause for this particular problem.

**Comment by jiwoonp** [comment]
Thanks for pointing that out! I downloaded the protein database as you suggested and was able to get the taxIDs.

I also just realized that a part of my data has the GenBank accession numbers, not NCBI (as you can see from `head(mydata[,2], 10)` above, the fifth entry is in GenBank format). Is my understanding correct that the `accessionToTaxa` function only works for the NCBI accession numbers (I mean the ones formatted with the "WP_####")?

**Comment by sherrillmix** [comment]
It's not so much that [MBJ15343.1](https://www.ncbi.nlm.nih.gov/protein/MBJ15343.1/) is a GenBank accession number. For example, [RAH17422.1](https://www.ncbi.nlm.nih.gov/protein/RAH17420.1) is a GenBank sequence from the same [bioproject](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA391943) and annotates fine. It seems that's it's specifically the autogenerated proteins from assembled genomes that are not available e.g. none of the proteins from MBJ15434's [genome assembly](https://www.ncbi.nlm.nih.gov/nuccore/PBFA01000003.1) seem to come up in any of the accession2taxid databases. Nor do accession numbers from another [random assembly](https://www.ncbi.nlm.nih.gov/nuccore/NZWJ02000001.1) from that project. 

I guess NCBI do not make the accession to taxa IDs easily accessible for those sequences for some reason but happy to add to the package if there is in fact some easily accessible database.

**Comment by jiwoonp** [comment]
Hmm I'm not sure why some of these are failing, looks like I might just have to extract the IDs from the local blast database I used to retrieve these accession numbers. Thank you so much for your input!

**Comment by sherrillmix** [comment]
That's pretty annoying that the data is there on NCBI but apparently not easily obtainable. I guess part of the problem is that the problem sequences are cataloged as [identical protein groups alone](https://www.ncbi.nlm.nih.gov/search/all/?term=MBJ15343.1) whereas sequences that appear in the database are cataloged as [both identical protein groups and proteins](https://www.ncbi.nlm.nih.gov/search/all/?term=RAH17422.1). 

So I guess the question might be how to find a database of the taxonomic IDs for identical protein groups. But google is failing me and NCBI doesn't seem to have documented.

How did you generate your blast database? Perhaps I could add a function to parse that to catch these unannotated NCBI accessions.

**Comment by sherrillmix** [comment]
Also I think IPG aren't supposed to have a "taxa". They're supposed to be groups of identical proteins across organisms/samples. So an IPG accession should pull up a list of individual proteins each of which would have a taxonomy. 

So not sure what it would mean when a sequence is annotated only as an "IPG" and not as a "protein". But then a search for [specifically protein](https://www.ncbi.nlm.nih.gov/protein/MBJ15343.1) (not IPG) does pull up the protein in question even though it's not listed as a "protein" in the multi-database search. 

Seems pretty annoying although I suppose there's probably some logic to it.

**Comment by jiwoonp** [comment]
Yes, the [protein record you found above](https://www.ncbi.nlm.nih.gov/protein/MBJ15343.1) was why I initially misunderstood this issue as a GenBank accession vs NCBI accession thing.  I'll need to dig in to find out whether there was anything done in particular other than just downloading the nr database to the local desktop, but it seems like the taxonomy IDs can be pulled out using the blastdbcmd command.
