### ISSUE TITLE
Preparing SQL for only specific taxa

### ISSUE THREAD

**Issue by NenBarto** [sherrillmix/taxonomizr#46]
First of all, thank you so much for providing this package, it has provided an immense speed-up to my workflows.
The only issue I've found was the size of the download, which becomes tricky, especially if it has to be done every two weeks to have a fresh copy.
Two quick questions:
1. Is it possible to download only selected taxa (i.e. only vertebrates), and create an SQL for them to reduce download time and occupied space?
2. Is there any way to allow downloading from the stop point? Even just not re-downloading the already finished files would be helpful.
Thanks again! :)

**Comment by sherrillmix** [comment]
Yeah I agree the download is a pain. The package uses the R `curl` library which does have a [handle function](https://www.rdocumentation.org/packages/curl/versions/4.3.2/topics/handle) which could conceivably take a [resume option](https://curl.se/libcurl/c/CURLOPT_RESUME_FROM.html), I'm not sure if that functionality is exposed in the R implementation (particularly on Windows) though so I'll have to look into that.

I don't think it'd be easy to select out certain taxa. Maybe something clever with [NCBI's efetch](https://www.rdocumentation.org/packages/reutils/versions/0.2.2/topics/efetch) or I guess you might be able to query the accessions in question and get back taxonomy with efetch. Sounds potentially slow for large numbers of accessions but not much experience there.

Bigger picture-wise, are you assigning taxonomy to accession numbers or just working with the NCBI taxonomy directly? If the latter, you can skip downloading the very large accesssion2taxid files with `prepareDatabase(getAccessions=FALSE)`. If you are doing accession numbers then for many applications, I wonder if one needs to be on the cutting edge? Perhaps a slower refresh cycle wouldn't really lose much performance? Also are you also updating your nt/nr or other database every two weeks? Seems like without that then not much use in getting taxa ID for sequences that don't appear in your database.

**Comment by sherrillmix** [comment]
It looks like I probably could include a resume function. For example:

```
url<-'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'

outFile<-'taxdump.tar.gz'
failFile<-'taxdump.tar.gz.fail'
recoveryFile<-'taxdump.tar.gz.recover'

curl::curl_download(url,outFile,mode='wb',quiet=FALSE)
#while downloading in terminal: cp taxdump.tar.gz.curltmp taxdump.tar.gz.fail

h<-curl::new_handle('resume_from_large'=file.size(failFile))
curl::curl_download(url,recoveryFile,mode='wb',quiet=FALSE,handle=h)
file.append(failFile,recoveryFile)
```

```
> tools::md5sum(failFile)
               taxdump.tar.gz.fail 
"125ce9bd3143ad62cbce404ee6dbf4c9" 
> tools::md5sum(outFile)
                    taxdump.tar.gz 
"125ce9bd3143ad62cbce404ee6dbf4c9" 
```

A few notes for myself if I do incorporate it:
* `curl_download()` erroneously treats the `mode='ab'` as `mode='wb'` and overwrites file so need to download the remainder to a separate file then `file.append()`
* While downloading `curl_download` saves the file to outputFileName.curltmp
* `curl_download` cleans up after itself on failed downloads so the curltmp file isn't available when needed. [`curl_download`'s source](https://rdrr.io/cran/curl/src/R/download.R) shows that there's an `on.exit(unlink(tmp))` so I guess I could just copy their function and delete that line. 

But overall I'm debating whether it's smart to implement, I could imagine someone downloading half on Tuesday then continuing download on Wednesday but in the mean time NCBI has changed the file. I suppose I could check the current md5 against a stored md5 first to prevent that though. Or if anything went wrong the md5 wouldn't match NCBI's md5 file which we check after download so could also catch that way. 

So I guess I mildly talked myself into it but I do worry about adding some "unknown unknowns" fragility since download errors are likely to have some odd corner cases. I suppose if it's an explicit option that people have to opt in to then just extra functionality that doesn't hurt (except more maintenance on my end :) ).

**Comment by NenBarto** [comment]
Thanks for the quick reply! 
Would be much appreciated if the "resume download" option could be enabled. I understand that it is extra time to maintain - but the last week I've been unsuccessful in downloading it to both local machine and my university cluster - both ftp and http options were failing where they used to work before. 

As for using only selected taxa - if I understand correctly nodes.dmp and names.dmp are a starting point for download. If we were allowed to provide our own (presumably by just having an option to not rebuild them from scratch) that could solve the issue. And they can be edited and manipulated with other tools (https://github.com/guyleonard/taxdump_edit). I could be horribly wrong here, but happy to spend time to test this out.

Finally, yes, need both accession IDs and taxonomy identifiers, so unfortunately the whole database. And you're right, monthly updates sound more realistic. :)

Thanks again!

**Comment by sherrillmix** [comment]
It's easy enough to edit the names.dmp and nodes.dmp. They're just plain text csv with basically two important columns each taxId,name and parent,child. Delete every name you don't care about and delete every node not in chain you care about. But those are "small" files already and they do nothing to inform the subsequent download of accession2taxid so I don't think that would really help with anything. 

NCBI provides the accession2taxid as a single chunk so I'm not seeing an easy way to edit that without having downloaded it. I suppose you could edit as it streamed in and save only accession you care about but that would only help with hard drive space since you would still have to download the same size file.

**Comment by sherrillmix** [comment]
I'm seeing if the curl package maintainer wants to deal with the download issues:
https://github.com/jeroen/curl/issues/274
I'll give that a day or two and see if that helps with things. Otherwise I'll just kludge my own download function together.

**Comment by sherrillmix** [comment]
Sorry it took a while but the github version of the package should now be able to resume interrupted downloads thanks to an [update in the curl package](https://github.com/jeroen/curl/pull/285). I'll mark this closed but feel free to reopen or open a new issue if any further suggestions/problems.

**Comment by NenBarto** [comment]
Excellent news, thanks so much! :D
N.
