### ISSUE TITLE
Error: Problem creating sql file. Deleting. Error in rsqlite_import_file(conn@ptr, name, value, sep, eol, skip) :    RS_sqlite_import: /tmp/RtmpFiCHWM/file7bfd7d94f1c3 line 249184308 expected 2 columns of data but found 1 In addition: There were 50 or more warnings (use warnings() to see the first 50)

### ISSUE THREAD

**Issue by lychen83** [sherrillmix/taxonomizr#5]
Hello,

I have download the prot.accession2taxid.gz and the other 4 nul files. I checked them by md5 value. They are completely downloaded.
However, when I run  > read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql') , I got error:
Reading nucl_est.accession2taxid.gz.
Reading nucl_gb.accession2taxid.gz.
Reading nucl_gss.accession2taxid.gz.
Reading nucl_wgs.accession2taxid.gz.
Reading prot.accession2taxid.gz.
Reading in values. This may take a while.
Error: Problem creating sql file. Deleting.
_Error in rsqlite_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: /tmp/RtmpFiCHWM/file7bfd7d94f1c3 line 249184308 expected 2 columns of data but found 1_
In addition: There were 50 or more warnings (use warnings() to see the first 50)

I used R 3.43. Could you kindly give me any suggestion to resolve this problem? Thank you so much

Best wishes,

Chen

**Comment by sherrillmix** [comment]
Oops sorry about the slow response, I didn't get a notification of this issue for some reason.

I wonder if this is related to issue #4 (a malformatted entry in the NCBI data). Could you try installing the newest version from github with:

    devtools::install_github('sherrillmix/taxonomizr')

and let me know if that fixes things? If that doesn't fix it, then we'll have to dig a bit deeper. Thanks.

**Comment by sghignone** [comment]
Hello Scott,
I  am dealing with the same issue reported before, with the difference that 3 columns are expected this time instead of 2..

Here is the complete output of prepareDatabase

>\>prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
Content type 'unknown' length 48557903 bytes (46.3 MB)
==================================================
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid//nucl_gb.accession2taxid.gz'
Content type 'unknown' length 1915965215 bytes (1827.2 MB)
==================================================
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid//nucl_wgs.accession2taxid.gz'
Content type 'unknown' length 3381235037 bytes (3224.6 MB)
==================================================
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Preprocessing accession2taxid with read.accession2taxid()
Reading ./nucl_gb.accession2taxid.gz.
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
Reading ./nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip) : 
  RS_sqlite_import: /tmp/Rtmp6pHymq/file10c233a5d3af0 line 196 **expected 3 columns of data but found 1**
In addition: There were 50 or more warnings (use warnings() to see the first 50)`

I am using R v.3.6 and the development version 0.5.3  of taxonomizr from github.
Thanks for your kind attention

**Comment by sherrillmix** [comment]
Hmm. Let me check. I'm downloading the NCBI files now. Thanks for letting me know.

**Comment by sghignone** [comment]
Hi Scott. Further investigations push me to think I've run out of space in my /tmp. I can say that because on another machine with larger /tmp the problem is not occurring. So the solution you suggested to start R with TMPDIR=/path/to/tmp R might work (and it actually works if I set TMPDIR=/path/to/tmp in my .bashrc).
I cannot get it working in my Rstudio sessions....

**Comment by sghignone** [comment]
I have found this trick to overwrite the R_SESSION_TMPDIR when working with RStudio.

Create a .Renviron file in your home directory, and fill it as follows:

`TMP="path/to/tmp"`

Then restart R. Calling Sys.getenv(), you'll get:
```
[...]
R_SESSION_TMPDIR              /path/to/tmp/RtmpaRfOmm
TMP                           /path/to/tmp
```

This happens because the R documentation in ?tempdir says this:

>By default, tmpdir will be the directory given by tempdir(). This will be a subdirectory of the per-session temporary directory found by the following rule when the R session is started. The environment variables TMPDIR, TMP and TEMP are checked in turn and the first found which points to a writable directory is used: if none succeeds ‘/tmp’ is used. The path should not contain spaces. Note that setting any of these environment variables in the R session has no effect on tempdir(): the per-session temporary directory is created before the interpreter is started.


I hope it helps.

**Comment by sherrillmix** [comment]
Cool. I was just going to suggest `Sys.setenv` but don't have Rstudio to debug. Glad everything worked out.

**Comment by sghignone** [comment]
UPDATE. Something is still going wrong and I cannot understand why..

When calling prepareDatabase('accessionTaxa.sql'), I got this

>\>prepareDatabase('accessionTaxa.sql')
Downloading names and nodes with getNamesAndNodes()
./names.dmp, ./nodes.dmp already exist. Delete to redownload
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
./nucl_gb.accession2taxid.gz, ./nucl_wgs.accession2taxid.gz already exist. Delete to redownload
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Preprocessing accession2taxid with read.accession2taxid()
Reading ./nucl_gb.accession2taxid.gz.
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
Reading ./nucl_wgs.accession2taxid.gz.
Reading in values. This may take a while.
Adding index. This may also take a while.
Error in result_create(conn@ptr, statement) : database or disk is full

both from RStudio and CMD line. I have 2.5T free on this machine...so the problem is not about disk...

Ideas?

PS. The problem does not happen on another machine, running R version 3.4.4 and the same version of taxonomizr from GitHub

**Comment by sherrillmix** [comment]
The package is using sqlite for the database and sqlite3 can be a bit finicky with /tmp problems so I would guess that's the cause. I think it does not listen to R's internal environment variables but would listen to a TMPDIR set prior to starting R. If you start R with TMPDIR=/path/to/tmp R and rerun things is the database created correctly? If you wanted to keep everything internal to RStudio then I suppose you could do a system call within RStudio with something like.:
`system('TMPDIR=/path/to/tmp R -e "taxonomizr::prepareDatabase(\'accessionTaxa.sql\')"')`
