### ISSUE TITLE
Error: disk I/O error   In addition: Warning message:   Couldn't set synchronous mode: disk I/O error

### ISSUE THREAD

**Issue by Ilaria-Pirona** [sherrillmix/taxonomizr#55]
Good morning,
I'm currently using your library to run a Nextflow process in Google Cloud Batch, but I'm getting this error every execution roughly after 35 to 40 minutes.

`Command error:
  Error: disk I/O error
  In addition: Warning message:
  Couldn't set synchronous mode: disk I/O error
  Use `synchronous` = NULL to turn off this warning. 
  Execution halted`

The process in Nextflow is this one:

`process ACCESSION_TO_TAXA {

    container 'ilariap/taxonomizr_p:latest'
    disk '600 GB'

    input:
    tuple val(sample), path(input_file)
    path(acc_to_taxa_db)

    script:

    """
    acc_to_taxa.R --input ${input_file} --sample ${sample} --acc2node ${acc_to_taxa_db}
    """

    output:

    tuple val(sample), path("${sample}_*_matches_taxa.txt"), emit:taxa
    tuple val(sample), path("${sample}_*_matches_taxa_names.txt"), emit:taxa_names
}`

As you can see I provided as much disk space as possible to avoid filling the disk (other specifications: RAM 72GB, CPUs 16).

The SQLite file ("accessionTaxa.sql" from the prepareDatabase() function) was generated only once and it is saved and distributed via path to the processes, to save time and not generate it every time the code is started in R.

The R script is quite simple:

`con <- file(input_file, "r")
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( length(line) == 0 ) {
    break
  }

  read_id<-str_split(line, ",")[[1]][1]
  acc_codes<-str_split(line, ",")[[1]][-1]

  translated_codes<-c()
  codes_names<-c()

  for (a in acc_codes){

      taxaId<-accessionToTaxa(a,acc_to_taxa_db)

      taxa_names<-getTaxonomy(taxaId,acc_to_taxa_db)

      if ( !is.na(taxaId) ) {

        translated_codes<-c(translated_codes,taxaId)
        codes_names<-c(codes_names,taxa_names)

      }
   }`

Program versions inside the Docker image are:

RSQLite  "2.2.20" 
curl   "5.0.0"
taxonomizr "0.10.2"

Do you have any suggestions as to the cause of the occurrence of this error?

**Comment by sherrillmix** [comment]
How big is your input file? And if you run this with a subset of your data then does it completes successfully? If so, perhaps it's the tmp directory eventually filling up. SQLite doesn't really like to listen to directives to set the tmp directory so that's a pretty frequent problem, e.g. #5, although that's usually during database creation and I don't think I've seen it in the data processing stage of things before. 

Perhaps related is that I don't think most use cases iterate on a per line basis so it's possible that is generating more cruft than expected. It's a bit hard to track exact tmp usage since SQLite often unlinks its files as soon as created but keeps using them. Perhaps monitor /tmp to see if that's likely to be a problem?

And just generally, if it was me, I'd probably readLines the whole input file (or a much larger subset) and do something like:

```
lines<-readLines(con) #if necessary adding something like n=1e7 and while loop
read_id<-sapply(strsplit(lines,','),'[[',1)
acc_codes<-lapply(strsplit(lines,','),'[',-1)
taxaId<-accessionToTaxa(unlist(acc_codes),acc_to_taxa_db)
taxaName<-getTaxonomy(taxaId,acc_to_taxa_db)
out<-data.frame(id=rep(read_id,sapply(acc_codes,length)),acc_code=unlist(acc_codes),taxa_id=taxa_id,taxaName)
```

Didn't test that. But rough idea anyway.

**Comment by Ilaria-Pirona** [comment]
Thank you for the quick response,
my files range from 50 to 600 megabites. I am supposing it is a read/write permission issue on the database put in the bucket that  makes it impossible for me to complete the process.

Thank you for the suggestion, I am aware that it is not usual to iterate over the rows of a file in R and also over accession codes. But, my reads could also have hundreds of matches and I noticed that the _accessionToTaxa_ function returns a single NA if there are too many items in the list, while if I process them individually I can get some taxa ids.

**Comment by sherrillmix** [comment]
I believe sqlite often wants write permission to a database even if not editing it so that could be a good guess. Here also we're doing some temp tables and merges so it would probably need write for that. 

accessionToTaxa returning an NA would definitely be a bug. If you have a reproducible example, definitely submit an issue and I'll fix it or add documentation. In general, hundreds of matches is definitely not "large" and hundreds of megabytes shouldn't really be either.

**Comment by Ilaria-Pirona** [comment]
Good evening,
I confirm it was a matter of permission of the database.

I will close this issue and I will open a new one with few lines of my input file to reproduce the NA issue.

Thank you very much for being so helpful to me.

**Comment by sherrillmix** [comment]
Thanks! Glad it got straightened out and that's really helpful to know to lookout for permissions if anyone sees that error in the future. Definitely let me know if the NA issue continues. Good luck with your research.
