### ISSUE TITLE
Download failed with error: "FTP response timeout".

### ISSUE THREAD

**Issue by castle-ah** [sherrillmix/taxonomizr#67]
Hi,

I am having trouble with downloading database using this code
`> prepareDatabase('accessionTaxa.sql',types='prot')`

The error message is as follows:
```
Downloading names and nodes with getNamesAndNodes()
Download status: 1 done; 0 in progress. Total size: 62.73 Mb (100%)... done!             
Downloaded file: ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
Modified: 2024-07-30 09:29:25
Status: 226
Preprocessing names with read.names.sql()
Preprocessing nodes with read.nodes.sql()
Downloading accession2taxid with getAccession2taxid()
This can be a big (several gigabytes) download. Please be patient and use a fast connection.
Download status: 1 done; 0 in progress. Total size: 9157.39 Mb (100%)... done!             
An error occurred in resumableDownload(xx, yy, resume = resume):
  Download failed with error: "FTP response timeout". Progress is saved in ./prot.accession2taxid.gz.__TMP__ and continued download can be attempted by repeating the previous command.
Delete ./prot.accession2taxid.gz.__TMP__ or set resume=FALSE to start from scratch.
```
I deleted the downloaded file and tried again about 3 times, but the same situation comes up.

What can i do?

Thanks

**Comment by sherrillmix** [comment]
Hmm this sort of problem usually ends up being a hiccup with internet or (rarely) the NCBI site e.g. I just tried to download with the above command and didn't run into any issues. A few options:
- you don't necessarily have to delete the downloaded file. It should be able to recover from where it stopped (assuming no funny business garbled any of it).
- You could try using http instead of ftp e.g. `prepareDatabase('accessionTaxa.sql',types='prot',protocol='http')`
- Manually download http://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz (or ftp://...) and put in working directory and `prepareDatabase` will use that
- Just trying again on more stable internet/different time

Let me know if none of those work.
